version: "3.8"

services:
  eventum:
    image: eventum:latest
    container_name: eventum
    depends_on:
      - clickhouse
    ports:
      - "9474:9474"
    volumes:
      - ./config:/app/config/:rw  # rw is for keyring updates
      - ./logs:/app/logs/:rw

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_PASSWORD=default
